### ISSUE TITLE
LaTeX code produced, but no image rendered

### ISSUE THREAD

**Issue by hpdeifel** [johnbcoughlin/calctex#1]
First of all: This package looks very promising. I didn't know it yet, but I was waiting for something like this my whole life :smile: 

I have followed the instructions:

1. `(require 'calctex)`
2. Enter calc
3. enable `calctex-mode`
4. Enter some algebraic formula (e.g `'1/x`)

This prints `\frac{1}{x}` in the calc buffer, but doesn't actually render the image. Am I missing something? Also, I my Emacs instance starts lagging a lot after entering the first formula.

**Comment by johnbcoughlin** [comment]
I've added some installation instructions that were missing from the README. I think you might be missing one of the listed packages: `xcolor`, `xparse`, or `soul`.

**Comment by johnbcoughlin** [comment]
If installing those does not fix it, would you paste the contents of the `*CalcTeX Log*` buffer here?

**Comment by hpdeifel** [comment]
Those packages were already installed.

I have inspected the the `*CalcTeX Log*` buffer and noticed that it tried to write its output files into the directory ~/org/ltximg, which doesn't exists on my system. Creating it changed the failure mode: Now the images are actually created in the directory (I can see them there), but the buffer still contains only `\frac{x}{y}`. The log buffer only contains the output of `dvipng`, as in the version of this program.

As a side node, it would be nice if this image cache would default to `$XDG_CACHE_HOME/calctex` *and* be configurable via customize. But I guess that's a separate feature request.

**Comment by johnbcoughlin** [comment]
I agree; I've filed #7 and #8 to track your side note.

Are there any message in the `*Messages*` buffer? Or, if you `M-x toggle-debug-on-error`, does anything come up?

**Comment by hpdeifel** [comment]
Alright, I guess I found it.

My emacs is compiled without imagemagick support and the overlay images use that. Unfortunately, I'd like to not rely on imagemagick too much, because it has a track record of being insecure and buggy.

Do you need imagemagic here, or would a normal PNG image suffice? Even better, if `dvisvg` is installed, it could even use SVGs. Org-mode has a configuration options for this called `org-preview-latex-process-alist`

**Comment by johnbcoughlin** [comment]
Ah, I see. Thank you for your patience and investigation!

imagemagick is used here to scale down the PNGs, which are compiled to extra-high DPI. The default DPI/scale settings look pretty bad on my retina display. I filed #12 and #13 to track this.

I am more familiar than I'd like to admit with the various latex preview format options! `xelatex -> dvisvg` is a strong choice, but it's not as fast as `dvipng`. An extra 200ms or so of latency is pretty noticeable for this use case.
