### ISSUE TITLE
Fall back to normal png image display if imagemagick not available

### ISSUE THREAD

**Issue by johnbcoughlin** [johnbcoughlin/calctex#13]

**Comment by flexibeast** [comment]
Thanks for your work on this package - very impressive!

Just wanted to note i'm in the same boat as @hpdeifel re. #1: 

> My emacs is compiled without imagemagick support and the overlay images use that. Unfortunately, I'd like to not rely on imagemagick too much, because it has a track record of being insecure and buggy. 

Once i recompiled Emacs with ImageMagick 6 support, your package worked. But yes, for the reasons @hpdeifel stated, i prefer to compile and run Emacs without that library.

**Comment by johnbcoughlin** [comment]
@flexibeast thank you for the data point. I will prioritize this.

**Comment by johnbcoughlin** [comment]
Resolved by #20

**Comment by flexibeast** [comment]
Excellent! Thanks again for your work on this. :-)
