### ISSUE TITLE
create image directory if not existent

### ISSUE THREAD

**Issue by bymoz089** [johnbcoughlin/calctex#17]
I changed `calctex-latex-image-directory` to point at a ramdisk location ([tmpfs filesystem](https://en.wikipedia.org/wiki/Tmpfs)), which is completely empty after a system reboot.

To ensure that the directory of `calctex-latex-image-directory` is existent, I inserted an

    (make-directory calctex-latex-image-directory 'parents)

int my emacs init.el

Maybe, this should be done inside the package?

**Comment by johnbcoughlin** [comment]
I believe this is done now on [this line](https://github.com/johnbcoughlin/calctex/pull/15/files#diff-b00d10f6677eb5a01577fc6084c24741R16). I will have it create the parents as well.
