### ISSUE TITLE
Selections don't work without calc-highlight-selection-with-faces set

### ISSUE THREAD

**Issue by hpdeifel** [johnbcoughlin/calctex#18]
*now with imagemagick*

I'm not sure if this is a bug or expected behaviour. Typing

```
'f(x) = 1/x
j1
j1
```

selects `x` in standard calc. With calctex, the first `j1` selects `= 1/x` and the second one selects `f() = 1/x`, which doesn't make sense to me at all.

**Comment by hpdeifel** [comment]
Ok, I now realize that what's shown in the image is exactly what's not selected...

Maybe it failed to apply some kind of highlighting? I have all required latex packages installed and the log buffer doesn't contain anything suspicious.

**Comment by hpdeifel** [comment]
:tada: `calc-highlight-selection-with-faces` must be set to `t` for it to work

**Comment by johnbcoughlin** [comment]
Yet another setting I had enabled in my development and then forgot about! Thank you for filing.

The default selection highlighting is kind of weird. It either replaces the entire rest of the equation with `.`, or replaces the selected portion with `#` characters. I think the first results in a usable latex render.
