### ISSUE TITLE
How to control display style? 

### ISSUE THREAD

**Issue by Yevgnen** [johnbcoughlin/calctex#3]
Thanks for the great package. It opens a new door for me to write LaTeX.

<img width="234" alt="Screen Shot 2019-08-08 at 8 49 42 AM" src="https://user-images.githubusercontent.com/16749790/62667284-9025de80-b9b9-11e9-8795-0b7f3fa02b66.png">

I'm quite new to `LaTeX` and `calc.el`. Following the demo of README, when I press `Q`, the intermediate result looks like the above image, who to make it like `\sqrt{2 \pi \sigma^2}`? Also the `\exp` looks different from the demo in README.

**Comment by johnbcoughlin** [comment]
Good question. Calc has various [mode settings](https://www.gnu.org/software/emacs/manual/html_node/calc/Mode-Settings.html#Mode-Settings), which control things like the floating point precision, whether inexact values like `sqrt(2)` are evaluated numerically at all, and various algebraic simplification rules.

In this case, you want to enter "symbolic mode" by pressing `m s`. This will prevent it from expanding `sqrt(2)`, but will still separate the radical into three terms. To avoid that, you can put it into no-simplification mode with `m O`. These commands won't affect expressions already on the stack.

**Comment by Yevgnen** [comment]
Thanks for the details, that's quite a `calc.el` question!
