### ISSUE TITLE
Prune large file history?

### ISSUE THREAD

**Issue by Yevgnen** [johnbcoughlin/calctex#4]
It seems that there are some MP4 file histories in the repo. I use `straight.el` to install this package and it takes quite a long time the clone the whole repo. Will it possible to prune these histories using techniques like [this](https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository)?

<img width="296" alt="Screen Shot 2019-08-08 at 9 12 33 AM" src="https://user-images.githubusercontent.com/16749790/62668001-ae410e00-b9bc-11e9-9204-6ab1fb70042c.png">

**Comment by johnbcoughlin** [comment]
Good call, thank you for pointing that out and for the link. I'll see if I can prune the large files.

**Comment by johnbcoughlin** [comment]
All right, I believe a fresh clone of this repo should now be fast:

```
$ time git clone git@github.com:johnbcoughlin/calctex.git
Cloning into 'calctex'...
remote: Enumerating objects: 96, done.
remote: Counting objects: 100% (96/96), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 96 (delta 35), reused 95 (delta 34), pack-reused 0
Receiving objects: 100% (96/96), 1.16 MiB | 2.78 MiB/s, done.
Resolving deltas: 100% (35/35), done.
git clone git@github.com:johnbcoughlin/calctex.git  0.09s user 0.05s system 12% cpu 1.119 total
```
